### PR TITLE
Karaf Features Update

### PR DESCRIPTION
**Pull request by grkvlt**
Updates to #241 including package refactoring.

### CODE REVIEW

**Comment by grkvlt** [comment]
@CMoH the validate step of the build keeps failing for me, any ideas?
```
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.4:verify (validate-features) on project brooklyn-clocker-features: Unable to load features descriptors: Error -> [Help 1]
```

**Comment by CMoH** [comment]
Seems fine on the first look.

I would replace commit 536a7d3 with a new one that simply comments out the feature validation goal - most karaf projects have feature validation disabled anyway, and I can simply enable it during development by uncommenting it.

However, validation fails because of `brooklyn-locations-jclouds`, which is on my list to investigate, so it might be that soon we'll re-enable it.

**Comment by grkvlt** [comment]
@CMoH I think this can be merged now, but what Brooklyn changes are we waiting on to make this work properly with Karaf? I see plenty of OSGi PRs in brooklyn-server like https://github.com/apache/brooklyn-server/pull/73 still.

**Comment by grkvlt** [comment]
I am going to merge this now, to prevent things getting hugely out of sync and allow others to work on this feature

**Comment by grkvlt** [comment]
Integration testing passes locally now

**Pull request merged**
