### PR TITLE
Add deploy repo

### PR DESCRIPTION
**Pull request by neykov**
Based (but does not depend) on https://github.com/brooklyncentral/clocker/pull/88

### CODE REVIEW

**Comment by grkvlt** [comment]
@neykov So I just need to merge this and since it includes #88 that should just be closed automatically, right?

**Comment by neykov** [comment]
#88 won't be closed automatically. Better merge #88 first and after that this one.

**Comment by grkvlt** [comment]
The commits have the same ID (235cdbf) so it should be OK, I think

**Comment by grkvlt** [comment]
Yep, worked, both got closed. Nice!

**Comment by neykov** [comment]
Great, didn't know this is supported :)

**Pull request merged**
