### PR TITLE
Fixes to get Clocker running as an OSGi bundle.

### PR DESCRIPTION
**Pull request by neykov**
Additionally needed changes:
  * https://github.com/brooklyncentral/advanced-networking/pull/23
  * https://github.com/apache/incubator-brooklyn/pull/446
  * change Brooklyn's jclouds docker dependency to the one used in clocker (1.8.2-alpha-cloudsoft.6 atm)

### CODE REVIEW

**Comment by neykov** [comment]
Build error due to dependency on https://github.com/brooklyncentral/advanced-networking/pull/21

**Comment by grkvlt** [comment]
Waiting on consensus for  brooklyncentral/advanced-networking#21 but once that is merged, should be good to go here

**Comment by sjcorbett** [comment]
https://github.com/brooklyncentral/advanced-networking/pull/21 is merged and an updated snapshot has been published to [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/io/brooklyn/networking/).

**Comment by neykov** [comment]
Thanks @sjcorbett, rebased to trigger a new build.

**Comment by grkvlt** [comment]
OK @neykov this looks good now, so I'm happy to merge it

**Pull request merged**
