### PR TITLE
Remove external resources

### PR DESCRIPTION
**Pull request by grkvlt**
**Important** This is required to let the Kubernetes catalog entries load when there is no external (public Internet) connectivity available to AMP.

Updates `iconUrl` to point at local files with `classpath://` URIs and adds the icons as resources. Copies the [brooklyn-dns](https://github.com/brooklyncentral/brooklyn-dns) BOM file to the target Jar so that it can be imported from a `classpath://` URI also.

### CODE REVIEW

**Comment by andreaturli** [comment]
Why from http to classpath? Performance?

**Comment by andreaturli** [comment]
Ah no maybe it's for weird networks where those resources may be nor reachable

**Comment by grkvlt** [comment]
So that the BOM file can be loaded onto a Brooklyn server running somewhere that does not have Internet access, such as many large enterprises.

**Comment by drigodwin** [comment]
@grkvlt, have you checked if we have the rights to incorporate all these images in clocker? Do they meet whatever terms of use they have?

**Comment by grkvlt** [comment]
@drigodwin good point, will review the terms of use and update if required

**Comment by grkvlt** [comment]
See [guidelines](https://github.com/kubernetes/kubernetes/blob/master/logo/usage_guidelines.md) for Kubernetes, also others. Will document these links on the Wiki here.

**Comment by grkvlt** [comment]
@drigodwin have added license details for icons

**Pull request merged**
