### PR TITLE
Fix references to server-cert.pem and server-key.pem

### LINKED ISSUE #122: 0.8.2 cannot find conf/server-cert.pem
Downloaded v0.8.2 from clocker.io and ran `./bin/clocker.sh jclouds:softlayer:ams01`. The installation of the DockerHosts failed with this exception:

```
2015-06-23 18:41:26,707 WARN  b.e.b.AbstractSoftwareProcessDriver [brooklyn-execmanager-uSWx77bc-85]: Error copying runtime resources
java.lang.RuntimeException: Error getting resource 'conf/server-cert.pem' for DockerHostImpl{id=AxGXNjjR}: java.io.IOException: 'conf/server-cert.pem' not found on classpath or filesystem
	at brooklyn.util.ResourceUtils.getResourceFromUrl(ResourceUtils.java:290) ~[brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	at brooklyn.location.basic.SshMachineLocation.installTo(SshMachineLocation.java:809) ~[brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.AbstractSoftwareProcessSshDriver.copyResource(AbstractSoftwareProcessSshDriver.java:368) ~[brooklyn-software-base-0.7.0-20150603.164055-252.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.AbstractSoftwareProcessDriver.copyResource(AbstractSoftwareProcessDriver.java:417) ~[brooklyn-software-base-0.7.0-20150603.164055-252.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.AbstractSoftwareProcessDriver.copyRuntimeResources(AbstractSoftwareProcessDriver.java:346) ~[brooklyn-software-base-0.7.0-20150603.164055-252.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.AbstractSoftwareProcessDriver$9.run(AbstractSoftwareProcessDriver.java:155) [brooklyn-software-base-0.7.0-20150603.164055-252.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_51]
	at brooklyn.util.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:337) [brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	at brooklyn.util.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:469) [brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
Caused by: java.io.IOException: 'conf/server-cert.pem' not found on classpath or filesystem
	at brooklyn.util.ResourceUtils.getResourceFromUrl(ResourceUtils.java:287) ~[brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	... 12 common frames omitted
```

### PR DESCRIPTION
**Pull request by sjcorbett**
Files in conf/ are available in the root of the classpath.

Fixes #122.

### CODE REVIEW

**Comment by sjcorbett** [comment]
Well, it fixes the deployment of Clocker at least. Subsequent applications fail with a monster number of errors repeating:

```
2015-06-23 20:13:13,576 WARN  b.l.jclouds.JcloudsLocation [brooklyn-execmanager-Hs0RMvsD-201]: Attempt #1/1 to obtain machine threw error: com.google.inject.CreationException: Guice creation errors:

1) Error in custom provider, java.lang.RuntimeException: java.io.FileNotFoundException: server-cert.pem (No such file or directory)
  while locating org.jclouds.http.okhttp.config.OkHttpCommandExecutorServiceModule$OkHttpClientProvider
  at org.jclouds.http.okhttp.config.OkHttpCommandExecutorServiceModule.configure(OkHttpCommandExecutorServiceModule.java:51)
  while locating com.squareup.okhttp.OkHttpClient
    for parameter 7 at org.jclouds.http.okhttp.OkHttpCommandExecutorService.<init>(OkHttpCommandExecutorService.java:70)
  while locating org.jclouds.http.okhttp.OkHttpCommandExecutorService
  at org.jclouds.http.okhttp.config.OkHttpCommandExecutorServiceModule.configure(OkHttpCommandExecutorServiceModule.java:50)
  while locating org.jclouds.http.HttpCommandExecutorService
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: server-cert.pem (No such file or directory)
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at org.jclouds.docker.suppliers.SSLContextWithKeysSupplier.get(SSLContextWithKeysSupplier.java:84)
	at org.jclouds.docker.config.DockerOkHttpClientSupplier.get(DockerOkHttpClientSupplier.java:48)
	at org.jclouds.docker.config.DockerOkHttpClientSupplier.get(DockerOkHttpClientSupplier.java:29)
	at org.jclouds.http.okhttp.config.OkHttpCommandExecutorServiceModule$OkHttpClientProvider.get(OkHttpCommandExecutorServiceModule.java:71)
	at org.jclouds.http.okhttp.config.OkHttpCommandExecutorServiceModule$OkHttpClientProvider.get(OkHttpCommandExecutorServiceModule.java:54)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:55)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:402)
	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:326)
	at org.jclouds.ContextBuilder.buildView(ContextBuilder.java:608)
	at org.jclouds.ContextBuilder.buildView(ContextBuilder.java:588)
	at org.jclouds.ContextBuilder.build(ContextBuilder.java:581)
	at brooklyn.location.jclouds.ComputeServiceRegistryImpl.findComputeService(ComputeServiceRegistryImpl.java:136)
	at brooklyn.location.jclouds.JcloudsLocation.obtainOnce(JcloudsLocation.java:617)
	at brooklyn.location.jclouds.JcloudsLocation.obtain(JcloudsLocation.java:581)
	at brooklyn.entity.container.docker.DockerContainerImpl.createLocation(DockerContainerImpl.java:453)
	at brooklyn.entity.container.docker.DockerContainerImpl.start(DockerContainerImpl.java:570)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:149)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at brooklyn.util.GroovyJavaMethods.invokeMethodOnMetaClass(GroovyJavaMethods.groovy:144)
	at brooklyn.management.internal.AbstractManagementContext.invokeEffectorMethodLocal(AbstractManagementContext.java:286)
	at brooklyn.management.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:310)
	at brooklyn.management.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:250)
	at brooklyn.entity.basic.MethodEffector.call(MethodEffector.java:149)
	at brooklyn.entity.trait.Startable$StartEffectorBody.call(Startable.java:57)
	at brooklyn.entity.trait.Startable$StartEffectorBody.call(Startable.java:51)
	at brooklyn.entity.effector.EffectorTasks$EffectorBodyTaskFactory$1.call(EffectorTasks.java:83)
	at brooklyn.util.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:337)
	at brooklyn.util.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:469)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: server-cert.pem (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:116)
	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
	at com.google.common.io.CharSource.read(CharSource.java:162)
	at com.google.common.io.Files.toString(Files.java:367)
	at org.jclouds.docker.suppliers.SSLContextWithKeysSupplier.loadFile(SSLContextWithKeysSupplier.java:114)
	at org.jclouds.docker.suppliers.SSLContextWithKeysSupplier.get(SSLContextWithKeysSupplier.java:73)
	... 63 more

```

**Comment by grkvlt** [comment]
@sjcorbett I'm a little wary of merging this, since the code works as it stands, certainly @csabapalfi and myself have not seen this issue - I am able to provision a clean new VM, install Java and unpack the distribution, and it _just works_ for most values of works...

**Comment by sjcorbett** [comment]
@grkvlt Yes. See additional comments in #122 - I did not realise that you HAVE to run from the right directory otherwise things mysteriously fail.

**Comment by csabapalfi** [comment]
See https://github.com/brooklyncentral/clocker/pull/127 with a different fix for #123 which maintains the conf/ path for server-cert.pem and server-key.pem

**Comment by grkvlt** [comment]
Closing this as #127 has been merged

**Pull request closed without merging**
