### PR TITLE
Upgrade weave to 1.0.0

### PR DESCRIPTION
**Pull request by csabapalfi**
This PR upgrades clocker to use weave 0.11.2. As 1.0 was released in the meantime we're just going to upgrade to that.

### CODE REVIEW

**Comment by csabapalfi** [comment]
Hah, weave just released 1.0! :) Will update this PR to use that.

**Comment by grkvlt** [comment]
Agree, can you test that, and then update the PR, thanks.

**Comment by grkvlt** [comment]
@csabapalfi looks OK to me, but I'd like to test it myself before merging...

**Comment by csabapalfi** [comment]
Ok, thanks. I just finished my testing and it looks good.

**Comment by grkvlt** [comment]
+1

**Pull request merged**
